### ISSUE TITLE
`grls` fails on first release without pushed release branch

### ISSUE THREAD

**Issue by thisismydesign** [thisismydesign/autowow#14]
Set upstream or push beforehand?

```
nb-capagyi:dotenv_rails_db_tasks_fix csaba.apagyi$ aw grls
[1a843399] Running git status
[1a843399]      On branch master
[1a843399]      Your branch is up to date with 'origin/master'.
[1a843399]
[1a843399]      nothing to commit, working tree clean
[1a843399] Finished in 0.026 seconds with exit status 0 (successful)

[3e9e4de8] Running git push
[3e9e4de8] Finished in 3.343 seconds with exit status 0 (successful)

[3fcea5fd] Running git checkout release
[3fcea5fd] Finished in 0.026 seconds with exit status 1 (failed)

[45c27a6a] Running git checkout -b release
[45c27a6a] Finished in 0.036 seconds with exit status 0 (successful)

[54197498] Running git pull
[54197498] Finished in 3.439 seconds with exit status 1 (failed)

[3275bed6] Running git checkout master
[3275bed6] Finished in 0.032 seconds with exit status 0 (successful)

Traceback (most recent call last):
        14: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/bin/aw:23:in `<main>'
        13: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/bin/aw:23:in `load'
        12: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/bin/aw:5:in `<top (required)>'
        11: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        10: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         9: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         8: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         7: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/cli.rb:34:in `gem_release'
         6: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/features/gem.rb:20:in `gem_release'
         5: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/features/vcs.rb:157:in `on_branch'
         4: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/features/vcs.rb:250:in `keep_changes'
         3: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/features/vcs.rb:166:in `block in on_branch'
         2: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/features/gem.rb:21:in `block in gem_release'
         1: from /Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/autowow-0.9.1/lib/autowow/executor.rb:40:in `run'
/Users/csaba.apagyi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/tty-command-0.7.0/lib/tty/command.rb:105:in `run': Running `git pull` failed with (TTY::Command::ExitError)
  exit status: 1
  stdout: Nothing written
  stderr: There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> release
```

**Comment by thisismydesign** [comment]
Should have a create and push branch command.
