### ISSUE TITLE
`aw bm` popped git stash even though it did not stash before

### ISSUE THREAD

**Issue by thisismydesign** [thisismydesign/autowow#16]
```
Traceback (most recent call last):
        11: from /home/vagrant/.rvm/gems/ruby-2.5.1/bin/aw:23:in `<main>'
        10: from /home/vagrant/.rvm/gems/ruby-2.5.1/bin/aw:23:in `load'
         9: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/autowow-0.14.0/bin/aw:5:in `<top (required)>'
         8: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
         7: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         6: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         5: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         4: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/autowow-0.14.0/lib/autowow/cli.rb:35:in `branch_merged'
         3: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/autowow-0.14.0/lib/autowow/features/vcs.rb:188:in `branch_merged'
         2: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/autowow-0.14.0/lib/autowow/features/vcs.rb:262:in `keep_changes'
         1: from /home/vagrant/.rvm/gems/ruby-2.5.1/gems/autowow-0.14.0/lib/autowow/executor.rb:70:in `run'
/home/vagrant/.rvm/gems/ruby-2.5.1/gems/tty-command-0.8.1/lib/tty/command.rb:106:in `run': Running `git stash pop` failed with (TTY::Command::ExitError)
  exit status: 1
  stdout: Nothing written
  stderr: No stash found.
```

**Comment by thisismydesign** [comment]
It's possible that `git stash` was called but it didn't create a stash:
```
$ git stash
No local changes to save
```

Couldn't reproduce so far, tried:
- not added changes
